# Generated by Django 3.2.19 on 2024-12-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=50)),
                ('date_of_attendance', models.DateField()),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('present', 'Present'), ('on_leave', 'On Leave')], max_length=10)),
            ],
        ),
    ]
