<<<<<<< HEAD
# Generated by Django 3.2.19 on 2024-12-18 10:33

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.19 on 2024-12-03 11:20

from django.db import migrations, models
>>>>>>> fd6d0b8c5e27194f5f4161022f1ccf50c9d23821


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('employee', '0001_initial'),
=======
>>>>>>> fd6d0b8c5e27194f5f4161022f1ccf50c9d23821
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('date_of_attendance', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
=======
                ('employee', models.CharField(max_length=50)),
                ('date_of_attendance', models.DateField()),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('present', 'Present'), ('on_leave', 'On Leave')], max_length=10)),
>>>>>>> fd6d0b8c5e27194f5f4161022f1ccf50c9d23821
            ],
        ),
    ]
