# Generated by Django 3.2.19 on 2024-12-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='employee',
            new_name='employee_name',
        ),
    ]
