<<<<<<< HEAD
# Generated by Django 3.2.19 on 2024-12-18 10:33
=======
# Generated by Django 3.2.19 on 2024-12-03 09:43
>>>>>>> fd6d0b8c5e27194f5f4161022f1ccf50c9d23821

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
<<<<<<< HEAD
=======
                ('head', models.CharField(max_length=50)),
>>>>>>> fd6d0b8c5e27194f5f4161022f1ccf50c9d23821
                ('description', models.TextField()),
            ],
        ),
    ]
